version: 2
updates:
  - package-ecosystem: composer
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: '14:00'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
      day: monday
      time: '14:30'
      timezone: America/Los_Angeles
    open-pull-requests-limit: 5
